### ISSUE TITLE
[Bug]: showing extra dot when listing repository

### ISSUE THREAD

**Issue by qweeah** [project-zot/zot#1081]
### zot version

v.1.4.3 minimal linux amd64 container

### Describe the bug

If an oci-layout folder is mounted to the root of zot's storage, then when listing repositories via [http api](https://docs.docker.com/registry/spec/api/#listing-repositories), an extra dot will be shown in the list.

### To reproduce

1. Configuration
Download a tarball image in oci-layout and enter the root folder, where `index.json`, `oci-layout` and `blobs` folder are in.

1. Client tool used
Ubuntu 20.04
Docker Engine 20.10.18
curl 7.68.0

1. Seen error
```console
docker run --name zot --rm -dp 6000:5000 -v $(pwd):/var/lib/registry ghcr.io/project-zot/zot-minimal-linux-amd64:latest
curl http://localhost:6000/v2/_catalog
```
The result of curl cmd will be:
```
{"repositories":["."]}
```
 I think it's a bug since I cannot use `.` as the repository name to access its images or artifacts. Correct me if I was wrong and there are some way to access the dot repository.

### Expected behavior

{"repositories":[]}

**Comment by rchincha** [comment]
@qweeah this sounds like a bug, triaging it. Thanks for filing the issue.

**Comment by andaaron** [comment]
Hi @qweeah, by design the root directory should not be an oci layout.
They root directory is supposed to contain multiple subdirectories, each of these subdirectories being oci layouts, one per repository. Each of these subdirectories would contain its own index.json, oci-layout and blobs.

In any case we have fixed `.` showing up in this API in case of this misconfiguration, as part of https://github.com/project-zot/zot/pull/1068.
