### ISSUE TITLE
Root access for skopeo in Makefile

### ISSUE THREAD

**Issue by IonutCraciun** [project-zot/zot#138]
Hello guys,

Why are you using sudo for skopeo operations?
Example: https://github.com/project-zot/zot/blob/main/Makefile#L50

**Comment by shimish2** [comment]
Sorry for late reply, I did not got any notification when this issue was created and didn't check the Issues tab for a while. 

This was needed to run skopeo inside travis ci build and without sudo it returns this error 

Error: error running newgidmap: exec: "newgidmap": executable file not found in $PATH: 
ERRO[0000] error running newgidmap: : exec: "newgidmap": executable file not found in $PATH 
ERRO[0000] (unable to determine exit status)

**Comment by andaaron** [comment]
Seems to be an issue with skopeo installed by https://github.com/project-zot/zot/blob/main/.github/workflows/ci-cd.yml#L51.
let's replace with skopeo installed using apt.

**Comment by andaaron** [comment]
Done
