### ISSUE TITLE
[Bug]: requested access to the resource is denied

### ISSUE THREAD

**Issue by BorisKofman** [project-zot/zot#1570]
### zot version

v2.0.0-rc5

### Describe the bug

requested access to the resource is denied with not default docker repo
example I have docker repo https://docker.io/test
when I trying to pull from localhost:5000/test/hybrid-adm:hybrid it give error in pulling images.

### To reproduce

1. Configuration
`          "sync": {
            "credentialsFile": "/secret/dockercfg.json",
            "enable": true,
            "registries": [
            {
              "urls": [
                "https://docker.io/test"
              ],
              "content": [
              {
                "destination": "/test",
                "prefix": "**"
              }
              ],
              "onDemand": true,
              "tlsVerify": true
            }
            ]
          }`
2. Client tool used
3. Seen error
`
{"level":"error","error":"reading manifest hybrid in docker.io/library/hybrid-adm: requested access to the resource is denied","repo":"hybrid-adm","reference":"hybrid","goroutine":77,"caller":"zotregistry.io/zot/pkg/extensions/sync/service.go:361","time":"2023-07-02T17:35:15.044407894Z","message":"couldn't get upstream image manifest details"}
{"level":"error","error":"reading manifest hybrid in docker.io/library/hybrid-adm: requested access to the resource is denied","repository":"test/hybrid-adm","reference":"hybrid","goroutine":75,"caller":"zotregistry.io/zot/pkg/api/routes.go:1727","time":"2023-07-02T17:35:15.044625869Z","message":"error encounter while syncing image"}
`

**Comment by peusebiu** [comment]
Hello @BorisKofman,

For syncing private docker registries the docker registry URL should be: `https://docker.io`
then pull localhost:5000/test/hybrid-adm:hybrid should work, if credentials are also correctly set in /secret/dockercfg.json

```
    "docker.io": {
        "username": <user>,
        "password": <password>
    }
```

Thank you for your feedback!

**Comment by BorisKofman** [comment]
Hey Thank you 
did the changes from:
```
    "docker.io/test": {
        "username": <user>,
        "password": <password>
    }
```
to:
```
    "docker.io": {
        "username": <user>,
        "password": <password>
    }
```
but it still same issue.

**Comment by peusebiu** [comment]
@BorisKofman did you also changed the url from https://docker.io/test to https://docker.io ?

**Comment by andaaron** [comment]
If `test` is part of the repository name on docker, you don't need to add it under in the `destination` key.
That configuration is for creating a new folder on zot which si not present in the upstream. For example you want to place all images pulled from `docker` under `docker/`. So in this case it would end up under `localhost:5000/test/test/hybrid-adm:hybrid`. Notice the double `test`, one coming from original path on docker, one added by zot.

Can you try removing `"destination": "/test"` from zot configuration pull again?

**Comment by BorisKofman** [comment]
@andaaron tested not working error: ImagePullBackOff

**Comment by rchincha** [comment]
@BorisKofman just checking that you don't have any network access controls that can prevent downloads?

@peusebiu we should be able to test this locally, did something change upstream on dockerhub?

**Comment by peusebiu** [comment]
Yeah tested this locally and with his config I get the same exact error, after modifying the registry URL in both sync config and sync credentials, it's working.

The denied error comes from the fact that docker.io/library/hybrid-adm is not a public repo or doesn't exist.

my dockerhub user is peusebiu and I have a `zot` under repositories.

here is my zot config:
```
{
    "distspecversion":"1.1.0-dev",
    "storage": {
        "rootDirectory": "/tmp/zot_to_sync",
        "dedupe": false,
        "gc": false
    },
    "http": {
        "address": "127.0.0.1",
        "port": "8081"
    },
    "log": {
        "level": "debug"
    },
    "extensions": {
        "sync": {
            "credentialsFile": "/home/peusebiu/sync-auth-filepath.json",
            "registries": [
                {
			"urls": [
				"https://docker.io"
			],
			"onDemand": true,
			"tlsVerify": true,
                        "content": [
                            {
                                 "destination": "/peusebiu",
                                 "prefix": "**"
                           }
                    ]
                }
            ]
        }
    }
}
```

here are my sync credentials:
```
{
    "127.0.0.1:8080": {
        "username": "user",
        "password": "pass"
    },
    "docker.io": {
        "username": "peusebiu",
        "password": "password"
    }
}
```

This is how I queried, like @andaaron said I need to double "peusebiu" because of destination.

```
peusebiu@PEUSEBIU-FC130:~$ skopeo copy docker://127.0.0.1:8081/peusebiu/peusebiu/zot:tls5 oci:oci:oci --src-tls-verify=false
Getting image source signatures
Copying blob d0f82576f946 done
Copying blob a91c1ed460d2 skipped: already exists
Copying blob 98b9e799d13b done
Copying config 822bb49247 done
Writing manifest to image destination
Storing signatures
peusebiu@PEUSEBIU-FC130:~$
```

@BorisKofman can you give us your latest logs with the latest errors?

**Comment by andaaron** [comment]
Wait so the image we want to sync is `docker.io/test/library/hybrid-adm` or `docker.io/library/hybrid-adm`?

**Comment by BorisKofman** [comment]
@andaaron I have private repo so I am trying to sync docker.io/test/library/hybrid-adm
@peusebiu When I remove /test
Nginx:
`nginx.ingress.kubernetes.io/rewrite-target=/v2/$2`
I got error:
`{"level":"error","error":"reading manifest hybrid in docker.io/library/hybrid-adm: requested access to the resource is denied","image":"docker.io/library/hybrid-adm:hybrid","goroutine":28,"caller":"zotregistry.io/zot/pkg/extensions/sync/utils.go:655","time":"2023-07-04T10:04:39.141247939Z","message":"couldn't get upstream image manifest details"}`

**Comment by peusebiu** [comment]
@BorisKofman please give me the output of docker inspect <your repo>

**Comment by andaaron** [comment]
Assuming

nginx config:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-oci-ingress-v2
  namespace: test
  labels: k8slens-edit-resource-version: v1
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /v2/test/$2
spec:
   ingressClassName: nginxv2
   rules:
   - host: test
     http:
       paths:
         - path: /v2(/|$)(.*)
           pathType: ImplementationSpecific
           backend:
              service:
                 name: oci-middleware
                 port:
                    number: 5000
```

sync config:
```
    "sync": {
      "enable": true,
      "credentialsFile": "/secret/dockercfg.json",
      "registries": [
        {
          "urls": ["https://docker.io"],
          "content": [
            {
              "prefix": "**", 
              "destination": "/test"
            }
          ],
          "onDemand": true,
          "tlsVerify": true
        }
      ]
    }
```

So let me check if I get this right:
- the client makes calls to `zot:5000/hybrid-adm:hybrid`
- before the call reaches zot nginx configured with `nginx.ingress.kubernetes.io/rewrite-target=/v2/test/$2` modifies the url to add `test`, resulting in `zot:5000/test/hybrid-adm:hybrid`
- the call reaches zot, which is configured to use `"destination": "/test"`, so zot requests the image `docker.io/library/hybrid-adm` in order to copy it under destination `/test`
- and all of the above is working per your last message - and it makes sense to be working.

Now, assuming the above scenario is working, the ask is not clear to me, so.

A. You are confirming this is what you intend to configure and the issue is resolved.

OR

B. You want the client to have to use  `zot:5000/test/hybrid-adm:hybrid` to access the image originally from  `docker.io/library/hybrid-adm`. In which case you should
- remove the nginx configuration entirely, and that should be enough
- keep zot configuration the same as posted above

OR

C. You want the client to use  `zot:5000/hybrid-adm:hybrid` to copy the image originally at `docker.io/test/library/hybrid-adm` in which case I expect to work if you:
- remove the `"destination": "/test"` configuration from zot, as the image already has `test` in the path, and that will be used in zot as well
- keep nginx config the same as posted above

**Comment by BorisKofman** [comment]
@andaaron 
the client makes calls to zot:5000/test/hybrid-adm:hybrid
To access image in docker.io/test/libarary/hybrid-adm:hybrid
 
the original configuration for ingress is:
`nginx.ingress.kubernetes.io/rewrite-target: /v2/$2`
but the image access trying to pull from docker.io/libarary/hybrid-adm:hybrid in zot and got ImagePullBackOff 
after debugging it and trying to understand the issue I have found that when I add rewrite-target: ` /v2/test/$2` it work but it block from adding another repo example /test2 

What I am trying to do: 
Create Zot Middleware to pull our images from private docker.io repository diagram example: 

![oci registry architecture](https://github.com/project-zot/zot/assets/83969370/2b655d83-afd4-4ac9-90f8-52a83012ad7e)

RC4 works as expected without rewrite-target: test

**Comment by andaaron** [comment]
For this use case you it looks to me like
1. You don't need to add the `"destination": "/test"` in the zot config, as the repo names in zot match entirely the repo name in dockerhub.
2. You don't need to add any nginx rewrites, for the same reason.

Did you try this out? If it fails what are the zot errors?

**Comment by BorisKofman** [comment]
@andaaron Thanks Working!
