### ISSUE TITLE
[Bug]: API endpoint /v2/_oci/ext/discover delivers an invalid URL

### ISSUE THREAD

**Issue by mbshields** [project-zot/zot#1921]
### zot version

v2.0.0

### Describe the bug

The returned response JSON payload from this API command includes this URL:
    https://github.com/project-zot/zot/blob//pkg/extensions/_zot.md
This URL gives a 404.  The correct URL should be:
    https://github.com/project-zot/zot/blob/main/pkg/extensions/_zot.md

### To reproduce

1. With a local zot server running, send curl -X GET http://localhost:8080/v2/_oci/ext/discover
2. An example command output is: 
{
    "extensions": [
    {
        "name": "_zot",
        "url": "https://github.com/project-zot/zot/blob//pkg/extensions/_zot.md",
        "description": "zot registry extensions",
        "endpoints": ["/v2/_zot/ext/search", "/v2/_zot/ext/userprefs", "/v2/_zot/ext/mgmt"]
    }]
}
3. Put the "url" in a browser, get a 404

### Expected behavior

Expect a valid URL to the file "_zot.md"

**Comment by andaaron** [comment]
Hi @mbshields,

There is a variable which is used in that URL at build time. It basically contains the result of the command `git describe --tags --abbrev=0`.

The zot binary you are running was probably built in an environment where the command I mentioned above returns an empty string, so you get `https://github.com/project-zot/zot/blob//pkg/extensions/_zot.md` instead of `https://github.com/project-zot/zot/blob/<my_release_tag>/pkg/extensions/_zot.md` which you would normally get in a release build.
For example our latest release uses `https://github.com/project-zot/zot/blob/v2.0.0-rc6/pkg/extensions/_zot.md`.

We avoided using `main` because older binaries may not have been built with the same extensions available in the newer `main`.
