### ISSUE TITLE
introductory questions about zot

### ISSUE THREAD

**Issue by tamalsaha** [project-zot/zot#621]
Thanks for the open source work. We have been looking into possible options for OCI registries and Zot seems quite nice in terms to features. Are they are product users of Zot? How production ready is Zot? Is there any place where we can find roadmap/current limitations of Zot?

Thanks.

**Comment by rchincha** [comment]
Hi @tamalsaha , thanks for considering `zot`.

Some background first.

`zot` is a purely OCI dist-spec-only registry which means that we closely follow, participate and implement the community standards as and when they evolve. `zot` does not implement any other vendor specs in belief that OCI specs/standards is the way forward.

> Are they are product users of Zot? How production ready is Zot?

`zot` is in use by Cisco in their internal ci/cd pipelines for over 2 years. That said, your use case may be different and you can assess if it is a good fit by looking at our [configuration examples](https://github.com/project-zot/zot/tree/main/examples), [ci/cd pipeline](https://github.com/project-zot/zot/actions), and also companion tools such as [`zb`](https://github.com/project-zot/zot#benchmarking).

Furthermore, our build artifacts are readily available at:
https://github.com/project-zot/zot/releases
https://github.com/orgs/project-zot/packages?repo_name=zot

> Is there any place where we can find roadmap/current limitations of Zot?

All our project planning/tracking is public:
https://github.com/project-zot/zot/projects/1
https://github.com/project-zot/zot/issues
https://github.com/project-zot/zot/discussions

Current limitations of zot are:
1) a UI which should be available very soon (note that docker registry doesn't have one either)
2) our cloud driver support is currently limited to AWS only because that has been the primary ask from users
3) not a CNCF project, yet, also to be addressed very soon
